export const categories = [
  { name: "Tecnología", slug: "tecnologia" },
  { name: "General", slug: "general" },
  { name: "Salud y Bienestar", slug: "salud-y-bienestar" },
  { name: "Negocios y Finanzas", slug: "negocios-y-finanzas" },
  { name: "Educación", slug: "educacion" },
  { name: "Ciencia y Medio Ambiente", slug: "ciencia-y-medio-ambiente" },
  { name: "Deportes", slug: "deportes" },
  { name: "Entretenimiento y Cultura", slug: "entretenimiento-y-cultura" },
  { name: "Viajes y Turismo", slug: "viajes-y-turismo" },
  { name: "Comida y Gastronomía", slug: "comida-y-gastronomia" },
  { name: "Moda y Belleza", slug: "moda-y-belleza" },
  { name: "Política y Sociedad", slug: "politica-y-sociedad" },
  { name: "Automotriz", slug: "automotriz" },
  { name: "Inmobiliaria", slug: "inmobiliaria" },
  { name: "Legal y Jurídico", slug: "legal-y-juridico" },
  { name: "Hogar y Jardinería", slug: "hogar-y-jardineria" },
  { name: "Mascotas y Animales", slug: "mascotas-y-animales" },
  { name: "Familia y Crianza", slug: "familia-y-crianza" },
  { name: "Arte y Fotografía", slug: "arte-y-fotografia" },
  { name: "Marketing y Publicidad", slug: "marketing-y-publicidad" },
  { name: "Videojuegos y eSports", slug: "videojuegos-y-esports" },
  { name: "Religión y Espiritualidad", slug: "religion-y-espiritualidad" },
  { name: "Blockchain y Criptomonedas", slug: "blockchain-y-criptomonedas" },
]
